//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooksWeb.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to add author to favourites..
        /// </summary>
        public static string Author_add_favourite {
            get {
                return ResourceManager.GetString("Author_add_favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to remove author from favourites..
        /// </summary>
        public static string Author_delete_favourite {
            get {
                return ResourceManager.GetString("Author_delete_favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to create author rating..
        /// </summary>
        public static string AuthorRating_create {
            get {
                return ResourceManager.GetString("AuthorRating_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to delete author rating..
        /// </summary>
        public static string AuthorRating_delete {
            get {
                return ResourceManager.GetString("AuthorRating_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to load author ratings..
        /// </summary>
        public static string AuthorRating_load {
            get {
                return ResourceManager.GetString("AuthorRating_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to update author rating..
        /// </summary>
        public static string AuthorRating_update {
            get {
                return ResourceManager.GetString("AuthorRating_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to load authors..
        /// </summary>
        public static string AuthorsLoad {
            get {
                return ResourceManager.GetString("AuthorsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to add book to favourites..
        /// </summary>
        public static string Book_add_favourite {
            get {
                return ResourceManager.GetString("Book_add_favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to remove book from favourites..
        /// </summary>
        public static string Book_delete_favourite {
            get {
                return ResourceManager.GetString("Book_delete_favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to create book rating..
        /// </summary>
        public static string BookRating_create {
            get {
                return ResourceManager.GetString("BookRating_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to delete book rating..
        /// </summary>
        public static string BookRating_delete {
            get {
                return ResourceManager.GetString("BookRating_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to load book ratings..
        /// </summary>
        public static string BookRating_load {
            get {
                return ResourceManager.GetString("BookRating_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to update book rating..
        /// </summary>
        public static string BookRating_update {
            get {
                return ResourceManager.GetString("BookRating_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to load books..
        /// </summary>
        public static string BooksLoad {
            get {
                return ResourceManager.GetString("BooksLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Přihlašovací jméno nebo heslo je prázdné..
        /// </summary>
        public static string EmptyLoginOrPassword {
            get {
                return ResourceManager.GetString("EmptyLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Internal server error..
        /// </summary>
        public static string Internal500UserId {
            get {
                return ResourceManager.GetString("Internal500UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to change login..
        /// </summary>
        public static string LoginChange {
            get {
                return ResourceManager.GetString("LoginChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Uživatelské jméno je již v systému registrováno, použijte prosím jiné..
        /// </summary>
        public static string LoginExists {
            get {
                return ResourceManager.GetString("LoginExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Error loading newsposts..
        /// </summary>
        public static string NewsLoad {
            get {
                return ResourceManager.GetString("NewsLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to change password..
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zadaná hesla se neshodují..
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to register..
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Špatné přihlašovací jméno nebo heslo..
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Failed to sign in..
        /// </summary>
        public static string SignIn500 {
            get {
                return ResourceManager.GetString("SignIn500", resourceCulture);
            }
        }
    }
}
