//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BooksWeb.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Autor.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nejlépe hodnocení autoři.
        /// </summary>
        public static string BestRatedAuthors {
            get {
                return ResourceManager.GetString("BestRatedAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nejlépe hodnocené knihy.
        /// </summary>
        public static string BestRatedBooks {
            get {
                return ResourceManager.GetString("BestRatedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Bibliografie.
        /// </summary>
        public static string Bibliography {
            get {
                return ResourceManager.GetString("Bibliography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Datum narození.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zrušit.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Změnit.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Změnit heslo.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Místo.
        /// </summary>
        public static string Chart_Place {
            get {
                return ResourceManager.GetString("Chart_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Smazat recenzi.
        /// </summary>
        public static string DeleteRating {
            get {
                return ResourceManager.GetString("DeleteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upravit profil.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Upravit recenzi.
        /// </summary>
        public static string EditRating {
            get {
                return ResourceManager.GetString("EditRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Přidat do oblíbených.
        /// </summary>
        public static string Favourite_add {
            get {
                return ResourceManager.GetString("Favourite_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Odebrat z oblíbených.
        /// </summary>
        public static string Favourite_remove {
            get {
                return ResourceManager.GetString("Favourite_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Napište nám zpětnou vazbu....
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Pokročilé vyhledávání.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jméno autora.
        /// </summary>
        public static string Filter_autor {
            get {
                return ResourceManager.GetString("Filter_autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hodnocení.
        /// </summary>
        public static string Filter_hodnoceni {
            get {
                return ResourceManager.GetString("Filter_hodnoceni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný ISBN.
        /// </summary>
        public static string Filter_ISBN {
            get {
                return ResourceManager.GetString("Filter_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jméno.
        /// </summary>
        public static string Filter_jmeno {
            get {
                return ResourceManager.GetString("Filter_jmeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Národnost.
        /// </summary>
        public static string Filter_narodnost {
            get {
                return ResourceManager.GetString("Filter_narodnost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Název.
        /// </summary>
        public static string Filter_nazev {
            get {
                return ResourceManager.GetString("Filter_nazev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Počet stran.
        /// </summary>
        public static string Filter_pocet_stran {
            get {
                return ResourceManager.GetString("Filter_pocet_stran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Příjmení.
        /// </summary>
        public static string Filter_prijmeni {
            get {
                return ResourceManager.GetString("Filter_prijmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Resetovat filtr.
        /// </summary>
        public static string Filter_reset {
            get {
                return ResourceManager.GetString("Filter_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rok narození.
        /// </summary>
        public static string Filter_rok_narozeni {
            get {
                return ResourceManager.GetString("Filter_rok_narozeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rok vydání.
        /// </summary>
        public static string Filter_rok_vydani {
            get {
                return ResourceManager.GetString("Filter_rok_vydani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Žánr.
        /// </summary>
        public static string Filter_zanr {
            get {
                return ResourceManager.GetString("Filter_zanr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný od.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hledat.
        /// </summary>
        public static string Hledat {
            get {
                return ResourceManager.GetString("Hledat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Knihy.
        /// </summary>
        public static string Knihy {
            get {
                return ResourceManager.GetString("Knihy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Přihlašovací jméno.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Dozvědět se více....
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Moje recenze.
        /// </summary>
        public static string MyRating {
            get {
                return ResourceManager.GetString("MyRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Jméno.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Napište nám.
        /// </summary>
        public static string Napiste_nam {
            get {
                return ResourceManager.GetString("Napiste_nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registrace nového uživatele.
        /// </summary>
        public static string New_user_registration {
            get {
                return ResourceManager.GetString("New_user_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nové heslo.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Potvrdit nové heslo.
        /// </summary>
        public static string NewPasswordConfirm {
            get {
                return ResourceManager.GetString("NewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Přezdívka.
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nemáte účet?.
        /// </summary>
        public static string NoAccountYet {
            get {
                return ResourceManager.GetString("NoAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nemáte žádné oblíbené autory..
        /// </summary>
        public static string NoFavouriteAuthors {
            get {
                return ResourceManager.GetString("NoFavouriteAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nemáte žádné oblíbené knihy..
        /// </summary>
        public static string NoFavouriteBooks {
            get {
                return ResourceManager.GetString("NoFavouriteBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tento autor nemá žádné recenze. Napište tu první!.
        /// </summary>
        public static string NoRatings_author {
            get {
                return ResourceManager.GetString("NoRatings_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Tato kniha nemá žádné recenze. Napište tu první!.
        /// </summary>
        public static string NoRatings_book {
            get {
                return ResourceManager.GetString("NoRatings_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Novinky.
        /// </summary>
        public static string Novinky {
            get {
                return ResourceManager.GetString("Novinky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Oblíbené.
        /// </summary>
        public static string Oblibene {
            get {
                return ResourceManager.GetString("Oblibene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Oblíbené knihy.
        /// </summary>
        public static string Oblibene_knihy {
            get {
                return ResourceManager.GetString("Oblibene_knihy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Oblíbení autoři.
        /// </summary>
        public static string Oblibeni_autori {
            get {
                return ResourceManager.GetString("Oblibeni_autori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný  z 10.
        /// </summary>
        public static string OutOfTen {
            get {
                return ResourceManager.GetString("OutOfTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný stran.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Heslo.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Potrvdit heslo.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hodnocení.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Text recenze.
        /// </summary>
        public static string Rating_text {
            get {
                return ResourceManager.GetString("Rating_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Recenze.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Registrovaní uživatelé mohou využívat pokročilých funkcí portálu, kterými jsou například přidávání a správa oblíbených autorů a knih, hodnocení a psaní recenzí k autorům a knihám a v neposlední řadě psaní anonymní zpětné vazby, připomínek a přání správcům portálu..
        /// </summary>
        public static string ReasonsToRegister {
            get {
                return ResourceManager.GetString("ReasonsToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zaregistrovat.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Zaregistrujte se!.
        /// </summary>
        public static string Register_Link {
            get {
                return ResourceManager.GetString("Register_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Uložit.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Odeslat.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Přihlášený uživatel:.
        /// </summary>
        public static string SignedUser {
            get {
                return ResourceManager.GetString("SignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Přihlásit se.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Odhlásit se.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rok narození ↑.
        /// </summary>
        public static string Sort_authoryear_asc {
            get {
                return ResourceManager.GetString("Sort_authoryear_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rok narození ↓.
        /// </summary>
        public static string Sort_authoryear_desc {
            get {
                return ResourceManager.GetString("Sort_authoryear_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Řadit dle:.
        /// </summary>
        public static string Sort_by {
            get {
                return ResourceManager.GetString("Sort_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Příjmení A-Z.
        /// </summary>
        public static string Sort_lastname_asc {
            get {
                return ResourceManager.GetString("Sort_lastname_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Příjmení Z-A.
        /// </summary>
        public static string Sort_lastname_desc {
            get {
                return ResourceManager.GetString("Sort_lastname_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Název A-Z.
        /// </summary>
        public static string Sort_name_asc {
            get {
                return ResourceManager.GetString("Sort_name_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Název Z-A.
        /// </summary>
        public static string Sort_name_desc {
            get {
                return ResourceManager.GetString("Sort_name_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Národnost A-Z.
        /// </summary>
        public static string Sort_nationality_asc {
            get {
                return ResourceManager.GetString("Sort_nationality_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Národnost Z-A.
        /// </summary>
        public static string Sort_nationality_desc {
            get {
                return ResourceManager.GetString("Sort_nationality_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Počet stran ↑.
        /// </summary>
        public static string Sort_pages_asc {
            get {
                return ResourceManager.GetString("Sort_pages_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Počet stran ↓.
        /// </summary>
        public static string Sort_pages_desc {
            get {
                return ResourceManager.GetString("Sort_pages_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hodnocení ↑.
        /// </summary>
        public static string Sort_rating_asc {
            get {
                return ResourceManager.GetString("Sort_rating_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Hodnocení ↓.
        /// </summary>
        public static string Sort_rating_desc {
            get {
                return ResourceManager.GetString("Sort_rating_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rok vydání  ↑.
        /// </summary>
        public static string Sort_year_asc {
            get {
                return ResourceManager.GetString("Sort_year_asc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Rok vydání ↓.
        /// </summary>
        public static string Sort_year_desc {
            get {
                return ResourceManager.GetString("Sort_year_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Spisovatelé.
        /// </summary>
        public static string Spisovatele {
            get {
                return ResourceManager.GetString("Spisovatele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Knižní databáze.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný do.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Vaše zpráva....
        /// </summary>
        public static string Vase_zprava {
            get {
                return ResourceManager.GetString("Vase_zprava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Proč se registrovat?.
        /// </summary>
        public static string WhyRegister {
            get {
                return ResourceManager.GetString("WhyRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Napsat recenzi.
        /// </summary>
        public static string Write_rating {
            get {
                return ResourceManager.GetString("Write_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Žebříčky.
        /// </summary>
        public static string Zebricky {
            get {
                return ResourceManager.GetString("Zebricky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nejlepší autoři.
        /// </summary>
        public static string Zebricky_autori {
            get {
                return ResourceManager.GetString("Zebricky_autori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Nejlepší knihy.
        /// </summary>
        public static string Zebricky_knihy {
            get {
                return ResourceManager.GetString("Zebricky_knihy", resourceCulture);
            }
        }
    }
}
