# File: makefile
# Solution: IPK - Project 2 - ZETA - Sniffer
# Date: 12.4.2020
# Author: Jan Lorenc (xloren15)
# Faculty: Faculty of Information Technology VUT
# Description: This is a makefile for building, running and cleaning the project

proj=./src/ipk-sniffer.csproj

build: 
	dotnet build $(proj)

clean:
	dotnet clean $(proj)
	
restore:
	dotnet restore $(proj)