//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockFests.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockFests.BL.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new band..
        /// </summary>
        public static string BandCreate {
            get {
                return ResourceManager.GetString("BandCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this band..
        /// </summary>
        public static string BandDelete {
            get {
                return ResourceManager.GetString("BandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the band..
        /// </summary>
        public static string BandLoad {
            get {
                return ResourceManager.GetString("BandLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load bands from the database..
        /// </summary>
        public static string Bands500 {
            get {
                return ResourceManager.GetString("Bands500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the band.
        /// </summary>
        public static string BandSave {
            get {
                return ResourceManager.GetString("BandSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update this band..
        /// </summary>
        public static string BandUpdate {
            get {
                return ResourceManager.GetString("BandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to count available tickets..
        /// </summary>
        public static string CountTickets {
            get {
                return ResourceManager.GetString("CountTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard wasn&apos;t loaded successfully..
        /// </summary>
        public static string DashboardLoad {
            get {
                return ResourceManager.GetString("DashboardLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this login already exists.
        /// </summary>
        public static string ExistingLogin {
            get {
                return ResourceManager.GetString("ExistingLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this festival..
        /// </summary>
        public static string FestivalDelete {
            get {
                return ResourceManager.GetString("FestivalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the festival..
        /// </summary>
        public static string FestivalLoad {
            get {
                return ResourceManager.GetString("FestivalLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load festivals.
        /// </summary>
        public static string Festivals500 {
            get {
                return ResourceManager.GetString("Festivals500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the festival..
        /// </summary>
        public static string FestivalSave {
            get {
                return ResourceManager.GetString("FestivalSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have rights for this page.
        /// </summary>
        public static string InsufficientRights {
            get {
                return ResourceManager.GetString("InsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of date interval must be lower then end..
        /// </summary>
        public static string InvalidDateInterval {
            get {
                return ResourceManager.GetString("InvalidDateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove member..
        /// </summary>
        public static string MemberRemove {
            get {
                return ResourceManager.GetString("MemberRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band has to have at least 1 member..
        /// </summary>
        public static string MembersEmpty {
            get {
                return ResourceManager.GetString("MembersEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error occured..
        /// </summary>
        public static string Modal500Body {
            get {
                return ResourceManager.GetString("Modal500Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, try the action again. If the error persists, try later..
        /// </summary>
        public static string Modal500BodyExtension {
            get {
                return ResourceManager.GetString("Modal500BodyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string Modal500Header {
            get {
                return ResourceManager.GetString("Modal500Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new musician..
        /// </summary>
        public static string MusicianCreate {
            get {
                return ResourceManager.GetString("MusicianCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this musician..
        /// </summary>
        public static string MusicianDelete {
            get {
                return ResourceManager.GetString("MusicianDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the musician..
        /// </summary>
        public static string MusicianLoad {
            get {
                return ResourceManager.GetString("MusicianLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load musicians..
        /// </summary>
        public static string Musicians500 {
            get {
                return ResourceManager.GetString("Musicians500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update this musician..
        /// </summary>
        public static string MusicianUpdate {
            get {
                return ResourceManager.GetString("MusicianUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - Page not found.
        /// </summary>
        public static string Page404 {
            get {
                return ResourceManager.GetString("Page404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 - Internal server error.
        /// </summary>
        public static string Page500 {
            get {
                return ResourceManager.GetString("Page500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the performances overlap..
        /// </summary>
        public static string PerformanceOverlap {
            get {
                return ResourceManager.GetString("PerformanceOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new rating..
        /// </summary>
        public static string RatingCreate {
            get {
                return ResourceManager.GetString("RatingCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this rating..
        /// </summary>
        public static string RatingDelete {
            get {
                return ResourceManager.GetString("RatingDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update this rating..
        /// </summary>
        public static string RatingUpdate {
            get {
                return ResourceManager.GetString("RatingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register new user..
        /// </summary>
        public static string Register500 {
            get {
                return ResourceManager.GetString("Register500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an interpret..
        /// </summary>
        public static string RequiredInterpret {
            get {
                return ResourceManager.GetString("RequiredInterpret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is required..
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected tickets are no longer available. Please refresh page to get updated data..
        /// </summary>
        public static string ReservationConcurrency {
            get {
                return ResourceManager.GetString("ReservationConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reserve your ticket..
        /// </summary>
        public static string ReserveTicket {
            get {
                return ResourceManager.GetString("ReserveTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user name or password.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in..
        /// </summary>
        public static string SignIn500 {
            get {
                return ResourceManager.GetString("SignIn500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new stage..
        /// </summary>
        public static string StageCreate {
            get {
                return ResourceManager.GetString("StageCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this stage..
        /// </summary>
        public static string StageDelete {
            get {
                return ResourceManager.GetString("StageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage with this name already exists..
        /// </summary>
        public static string StageExists {
            get {
                return ResourceManager.GetString("StageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the stage..
        /// </summary>
        public static string StageSave {
            get {
                return ResourceManager.GetString("StageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to approve this ticket..
        /// </summary>
        public static string TicketApprove {
            get {
                return ResourceManager.GetString("TicketApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a ticket..
        /// </summary>
        public static string TicketCreate {
            get {
                return ResourceManager.GetString("TicketCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this ticket..
        /// </summary>
        public static string TicketDelete {
            get {
                return ResourceManager.GetString("TicketDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the ticket..
        /// </summary>
        public static string TicketLoad {
            get {
                return ResourceManager.GetString("TicketLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load tickets..
        /// </summary>
        public static string Tickets500 {
            get {
                return ResourceManager.GetString("Tickets500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update this ticket..
        /// </summary>
        public static string TicketUpdate {
            get {
                return ResourceManager.GetString("TicketUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create new user..
        /// </summary>
        public static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete this user..
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the user..
        /// </summary>
        public static string UserLoad {
            get {
                return ResourceManager.GetString("UserLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load users from the database..
        /// </summary>
        public static string Users500 {
            get {
                return ResourceManager.GetString("Users500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change new settings..
        /// </summary>
        public static string UserSettings500 {
            get {
                return ResourceManager.GetString("UserSettings500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update information about this user..
        /// </summary>
        public static string UserUpdate {
            get {
                return ResourceManager.GetString("UserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update user&apos;s password..
        /// </summary>
        public static string UserUpdatePassword {
            get {
                return ResourceManager.GetString("UserUpdatePassword", resourceCulture);
            }
        }
    }
}
