//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockFests.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Routes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Routes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockFests.BL.Resources.Routes", typeof(Routes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bands.
        /// </summary>
        public static string Bands {
            get {
                return ResourceManager.GetString("Bands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bands_Detail_{Id}.
        /// </summary>
        public static string Bands_Detail {
            get {
                return ResourceManager.GetString("Bands_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Bands/Detail/.
        /// </summary>
        public static string Bands_Detail_Url {
            get {
                return ResourceManager.GetString("Bands_Detail_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Dashboard.
        /// </summary>
        public static string Dashboard_Url {
            get {
                return ResourceManager.GetString("Dashboard_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festivals.
        /// </summary>
        public static string Festivals {
            get {
                return ResourceManager.GetString("Festivals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festivals_Detail_{Id}.
        /// </summary>
        public static string Festivals_Detail {
            get {
                return ResourceManager.GetString("Festivals_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Festivals/Detail/.
        /// </summary>
        public static string Festivals_Detail_Url {
            get {
                return ResourceManager.GetString("Festivals_Detail_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Festivals.
        /// </summary>
        public static string Festivals_Url {
            get {
                return ResourceManager.GetString("Festivals_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musicians.
        /// </summary>
        public static string Musicians {
            get {
                return ResourceManager.GetString("Musicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musicians_Detail_{Id}.
        /// </summary>
        public static string Musicians_Detail {
            get {
                return ResourceManager.GetString("Musicians_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Musicians/Detail/.
        /// </summary>
        public static string Musicians_Detail_Url {
            get {
                return ResourceManager.GetString("Musicians_Detail_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication_Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication_SignIn.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets_Detail_{Id}.
        /// </summary>
        public static string Tickets_Detail {
            get {
                return ResourceManager.GetString("Tickets_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Tickets/Detail/.
        /// </summary>
        public static string Tickets_Detail_Url {
            get {
                return ResourceManager.GetString("Tickets_Detail_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users_Detail_{Id}.
        /// </summary>
        public static string Users_Detail {
            get {
                return ResourceManager.GetString("Users_Detail", resourceCulture);
            }
        }
    }
}
