#!/bin/bash
#PBS -q qexp
#PBS -A OPEN-20-37
#PBS -l select=1:ncpus=36,vtune=2020_update3-GCC 
#PBS -l walltime=0:10:00
#PBS -m e
#PBS -N AVS-Advisor


cd $PBS_O_WORKDIR
ml CMake intel-compilers/2021.1.2 Advisor/2020_update3

rm -rf build_advisor
mkdir build_advisor
cd build_advisor

CC=icc CXX=icpc cmake ..
make


for calc in "ref" "batch" "line"; do
    rm -rf Advisor-$calc
    mkdir Advisor-$calc

    # Basic survey
    advixe-cl -collect survey -project-dir Advisor-$calc  -- ./mandelbrot -c $calc -s 4000


    # Roof line
    advixe-cl -collect tripcounts -flop -project-dir Advisor-$calc  -- ./mandelbrot -c $calc -s 4000
done