//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockFests.DAL.Seeds {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeedImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeedImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockFests.DAL.Seeds.SeedImages", typeof(SeedImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bruce_dickinson {
            get {
                object obj = ResourceManager.GetObject("bruce_dickinson", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] green_day_billie_armstrong {
            get {
                object obj = ResourceManager.GetObject("green_day_billie_armstrong", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] green_day_jason_white {
            get {
                object obj = ResourceManager.GetObject("green_day_jason_white", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] green_day_logo {
            get {
                object obj = ResourceManager.GetObject("green_day_logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] green_day_mike_dirnt {
            get {
                object obj = ResourceManager.GetObject("green_day_mike_dirnt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] green_day_tre_cool {
            get {
                object obj = ResourceManager.GetObject("green_day_tre_cool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] guns_and_roses_axl_rose {
            get {
                object obj = ResourceManager.GetObject("guns_and_roses_axl_rose", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] guns_and_roses_dizzy_reed {
            get {
                object obj = ResourceManager.GetObject("guns_and_roses_dizzy_reed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] guns_and_roses_duff_mckagan {
            get {
                object obj = ResourceManager.GetObject("guns_and_roses_duff_mckagan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] guns_and_roses_frank_ferrer {
            get {
                object obj = ResourceManager.GetObject("guns_and_roses_frank_ferrer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] guns_and_roses_logo {
            get {
                object obj = ResourceManager.GetObject("guns_and_roses_logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] guns_and_roses_melissa_reese {
            get {
                object obj = ResourceManager.GetObject("guns_and_roses_melissa_reese", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] guns_and_roses_richard_fortus {
            get {
                object obj = ResourceManager.GetObject("guns_and_roses_richard_fortus", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iron_maiden_adrian_smith {
            get {
                object obj = ResourceManager.GetObject("iron_maiden_adrian_smith", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iron_maiden_dave_murray {
            get {
                object obj = ResourceManager.GetObject("iron_maiden_dave_murray", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iron_maiden_janick_gers {
            get {
                object obj = ResourceManager.GetObject("iron_maiden_janick_gers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iron_maiden_logo {
            get {
                object obj = ResourceManager.GetObject("iron_maiden_logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iron_maiden_nicko_mcbrain {
            get {
                object obj = ResourceManager.GetObject("iron_maiden_nicko_mcbrain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] iron_maiden_steve_harris {
            get {
                object obj = ResourceManager.GetObject("iron_maiden_steve_harris", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] marilyn_manson {
            get {
                object obj = ResourceManager.GetObject("marilyn_manson", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] metallica_james_hetfield {
            get {
                object obj = ResourceManager.GetObject("metallica_james_hetfield", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] metallica_kirk_hammett {
            get {
                object obj = ResourceManager.GetObject("metallica_kirk_hammett", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] metallica_lars_urlich {
            get {
                object obj = ResourceManager.GetObject("metallica_lars_urlich", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] metallica_logo {
            get {
                object obj = ResourceManager.GetObject("metallica_logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] metallica_robert_trujillo {
            get {
                object obj = ResourceManager.GetObject("metallica_robert_trujillo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pearl_jam_eddie_vedder {
            get {
                object obj = ResourceManager.GetObject("pearl_jam_eddie_vedder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pearl_jam_jeff_ament {
            get {
                object obj = ResourceManager.GetObject("pearl_jam_jeff_ament", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pearl_jam_logo {
            get {
                object obj = ResourceManager.GetObject("pearl_jam_logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pearl_jam_matt_cameron {
            get {
                object obj = ResourceManager.GetObject("pearl_jam_matt_cameron", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pearl_jam_mike_mcready {
            get {
                object obj = ResourceManager.GetObject("pearl_jam_mike_mcready", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pearl_jam_stone_gossard {
            get {
                object obj = ResourceManager.GetObject("pearl_jam_stone_gossard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] slash {
            get {
                object obj = ResourceManager.GetObject("slash", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
