version: "3.8"
services:

    mongodb:
        image : mongo
        container_name: UPA_mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        networks:
            - app-tier

networks:
    app-tier:
        driver: bridge
